<a href="https://colab.research.google.com/github/mishkatnaveed14/python_programming_practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

**Numpy Arrays Creation method and properties**

In [8]:
# Arrays
# one dimensional arrays
one_dimensional_arr = np.array([1,2,34,5,6,8,9,9])
print(one_dimensional_arr)
# two-dimensional-array or matrix
two_dimensional_arr = np.array([[1,2,3,4,5],
                       [6,7,8,9,20]])
print(two_dimensional_arr)
# multi dimensional array or 3d array
three_dimensional_arr = np.array([[1,2,3,5,6,7,8],
                                  [2,7,8,9,9,0,0],
                                  [3,6,9,0,0,3,8]])
print(three_dimensional_arr)

[ 1  2 34  5  6  8  9  9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 20]]
[[1 2 3 5 6 7 8]
 [2 7 8 9 9 0 0]
 [3 6 9 0 0 3 8]]


In [16]:
# array with default values
# zeros function for future value
# np.zeroes(shapes(size))=>[(3) for 1d (3,3) 2d]
zeroes_array = np.zeros(34)
print(zeroes_array)
# ones function for future value
ones_array = np.ones((3,7)) # 3 rows and 7 columns
print(ones_array)
# full(shape,value)
filled_array = np.full((3,2),7) # np.full means that the array grid has 3 row and 2 coloumns and filled with 7
print(filled_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[7 7]
 [7 7]
 [7 7]]


In [18]:
# creating sequences of numbers in numpy same as range function
# arange(start,stop,step)
arr = np.arange(1,12,2) # returns numpy array
print(arr)



[ 1  3  5  7  9 11]


In [20]:
# creating identity matrices
# square matrix  => ones (1) in every column and zeroo else any where
# eye(size)
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Array prperties and operations**

In [3]:
# Array => properties-> calculations
# how to check the shape size type? to perform any operation NO. of dimensions
# how to check the shape odf any array when working on the multidimensional data
arr_2d_multi = np.array([[1,2,3,4],
                         [5,6,7,8]])
print(arr_2d_multi.shape)


(2, 4)


In [7]:
# size total number of elements in an array
# when we work with a big data set
arr = np.array([[10,20,30,45],
                [40,50,60,29]])
print(arr.size)

8


In [10]:
# ndim ==>> No.of dimensions ==> wen we deals 1d,2d,3d dimeneion data ndim helps to identidy that how many dimensions are exist in na array
# array.ndim() is ma dimensions nikalnay k liye 1d k liye 1 square brakets [], 2d ==> [[]], 3d ==> [[[]]]

array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3,4],[1,3,4,5]])
array_3d = np.array([[[1,2,7],[2,3,4],[1,4,5],[1,5,6]]])
print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)


1
2
3


In [15]:
# .dtype returns the data type
# we use to make  sure that all the values are in sae data type
arr_datatype = np.array([1,3,4,5,4])
print(arr_datatype.dtype)
arr_datatype = np.array([1.4,3.4,4.5,3.8,4.6])
print(arr_datatype.dtype)
arr_datatype = np.array(["1","3","4","5","4"])
print(arr_datatype.dtype)

int64
float64
<U1


In [21]:

# .astype change the datatype
# i want to change the text to num in numpy so we use astype(newtype[etc])
array_type = np.array([1.2,3.4,5.7])
print(array_type.dtype)
int_arr = array_type.astype(int)
print (int_arr)
print(int_arr.dtype)

float64
[1 3 5]
int64


In [23]:
# mathematical operations in numpy array without using loops
# operators ==> +, -, *, / , %
arra_operations = np.array([10,20,30])
print(arra_operations + 2)
print(arra_operations - 2)
print(arra_operations * 2)
print(arra_operations / 2)
print(arra_operations % 2)
print(arra_operations ** 2)



[12 22 32]
[ 8 18 28]
[20 40 60]
[ 5. 10. 15.]
[0 0 0]
[100 400 900]


In [24]:
# aggregation function ==> dta ma se summary data ma se stats nikalna sum nikalana jese stc
# np.sum(array) ==> add all
# np.mean(array) ==> calculate average
# np.min(array) ==> give the smallest value in the array
# np.max(array) ==> give the largest value in the array
# np.std(array) ==> stndard deviation
# np.var(array) ==> variations
array_aggregation = np.array([10,20,30,40,50])
print(np.sum(array_aggregation))
print(np.mean(array_aggregation))
print(np.min(array_aggregation))
print(np.max(array_aggregation))
print(np.std(array_aggregation))
print(np.var(array_aggregation))



150
30.0
10
50
14.142135623730951
200.0


**indexing or slicing**

In [33]:
# what is indexing ==> indexing we found specifc element at certain index
# slicing we obtain a certain part (start stop step )
# and we have advance topics like fancy indexing and boolean indexing

# INDEXING:
# one dimension array indeing
array_indexing = np.array([1,2,3,4,5,5])
print(array_indexing[2]) #3
print(array_indexing[4]) #5
print(array_indexing[-3]) #4
# two dimension array indexing
array2d_indexing = np.array([[1,2,3],
                             [1,9,0]])
print(array2d_indexing[0,2])

# SLICING:
# array[start:stop:step]
# array[start:stop] ==> start to end -1
# array[start:] ==> start to end
# array[:stop] ==> start to end -1
array_slicing = np.array([10,20,30,40,50,60,70,80])
print








3
5
4
3


'\narray[start:stop:step]\narray[start:stop] ==> start to end -1\narray[start:] ==> start to end\narray[:stop] ==> start to end -1\n'