<a href="https://colab.research.google.com/github/mishkatnaveed14/python_programming_practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Numpy Arrays Creation method and properties**

In [2]:
# Arrays
# one dimensional arrays
one_dimensional_arr = np.array([1,2,34,5,6,8,9,9])
print(one_dimensional_arr)
# two-dimensional-array or matrix
two_dimensional_arr = np.array([[1,2,3,4,5],
                       [6,7,8,9,20]])
print(two_dimensional_arr)
# multi dimensional array or 3d array
three_dimensional_arr = np.array([[1,2,3,5,6,7,8],
                                  [2,7,8,9,9,0,0],
                                  [3,6,9,0,0,3,8]])
print(three_dimensional_arr)

[ 1  2 34  5  6  8  9  9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 20]]
[[1 2 3 5 6 7 8]
 [2 7 8 9 9 0 0]
 [3 6 9 0 0 3 8]]


In [ ]:
# array with default values
# zeros function for future value
# np.zeroes(shapes(size))=>[(3) for 1d (3,3) 2d]
zeroes_array = np.zeros(34)
print(zeroes_array)
# ones function for future value
ones_array = np.ones((3,7)) # 3 rows and 7 columns
print(ones_array)
# full(shape,value)
filled_array = np.full((3,2),7) # np.full means that the array grid has 3 row and 2 coloumns and filled with 7
print(filled_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[7 7]
 [7 7]
 [7 7]]


In [55]:
# creating sequences of numbers in numpy same as range function
# arange(start,stop,step)
arr = np.arange(1,12,1) # returns numpy array
print(arr)



[ 1  2  3  4  5  6  7  8  9 10 11]


In [5]:
# creating identity matrices
# square matrix  => ones (1) in every column and zeroo else any where
# eye(size)
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Array prperties and operations**

In [6]:
# Array => properties-> calculations
# how to check the shape size type? to perform any operation NO. of dimensions
# how to check the shape odf any array when working on the multidimensional data
arr_2d_multi = np.array([[1,2,3,4],
                         [5,6,7,8]])
print(arr_2d_multi.shape)


(2, 4)


In [7]:
# size total number of elements in an array
# when we work with a big data set
arr = np.array([[10,20,30,45],
                [40,50,60,29]])
print(arr.size)

8


In [ ]:
# ndim ==>> No.of dimensions ==> when we deals 1d,2d,3d dimeneion data ndim helps to identify that how many dimensions are exist in na array
# array.ndim() is ma dimensions nikalnay k liye 1d k liye 1 square brakets [], 2d ==> [[]], 3d ==> [[[]]]

array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3,4],[1,3,4,5]])
array_3d = np.array([[[1,2,7],[2,3,4],[1,4,5],[1,5,6]]])
print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)


1
2
3


In [ ]:
# .dtype returns the data type
# we use to make  sure that all the values are in sae data type
arr_datatype = np.array([1,3,4,5,4])
print(arr_datatype.dtype)
arr_datatype = np.array([1.4,3.4,4.5,3.8,4.6])
print(arr_datatype.dtype)0
arr_datatype = np.array(["1","3","4","5","4"])
print(arr_datatype.dtype)

int64
float64
<U1


In [10]:

# .astype change the datatype
# i want to change the text to num in numpy so we use astype(newtype[etc])
array_type = np.array([1.2,3.4,5.7])
print(array_type.dtype)
int_arr = array_type.astype(int)
print (int_arr)
print(int_arr.dtype)

float64
[1 3 5]
int64


In [11]:
# mathematical operations in numpy array without using loops
# operators ==> +, -, *, / , %
arra_operations = np.array([10,20,30])
print(arra_operations + 2)
print(arra_operations - 2)
print(arra_operations * 2)
print(arra_operations / 2)
print(arra_operations % 2)
print(arra_operations ** 2)



[12 22 32]
[ 8 18 28]
[20 40 60]
[ 5. 10. 15.]
[0 0 0]
[100 400 900]


In [ ]:
# aggregation function ==> data ma se summary data ma se stats nikalna sum nikalana jese stc
# np.sum(array) ==> add all
# np.mean(array) ==> calculate average
# np.min(array) ==> give the smallest value in the array
# np.max(array) ==> give the largest value in the array
# np.std(array) ==> stndard deviation
# np.var(array) ==> variations
array_aggregation = np.array([10,20,30,40,50])
print(np.sum(array_aggregation))
print(np.mean(array_aggregation))
print(np.min(array_aggregation))
print(np.max(array_aggregation))
print(np.std(array_aggregation))
print(np.var(array_aggregation))



150
30.0
10
50
14.142135623730951
200.0


**indexing or slicing**

In [13]:
# what is indexing ==> indexing we found specifc element at certain index
# slicing we obtain a certain part (start stop step )
# and we have advance topics like fancy indexing and boolean indexing

# INDEXING:
# one dimension array indeing
array_indexing = np.array([1,2,3,4,5,5])
print(array_indexing[2]) #3
print(array_indexing[4]) #5
print(array_indexing[-3]) #4
# two dimension array indexing
array2d_indexing = np.array([[1,2,3],
                             [1,9,0]])
print(array2d_indexing[0,2])

# SLICING:
# also starts with 0 indexing
# array[start:stop:step]
# array[start:stop] ==> start to end -1
# array[start:] ==> start to end
# array[:stop] ==> start to end -1
array_slicing = np.array([10,20,30,40,50,60,70,80])
print(array_slicing[0:])
print(array_slicing[0:2])
print(array_slicing[1:7:2])
print(array_slicing[:6])
print(array_slicing[::-1]) # reverse the array

# FANCY INDEXING:
# selecting multiple elements at once for non sequentional values and made the copy of an array 0 means 2 means 4 means k mujhe o 2 or 4 index pr jo bhi element hain mujhe wo chahiye 
fancy_indexing = np.array([10,20,30,40,50])
print(fancy_indexing[[0,2,4]])

# FILTERING DATA OR BOOLEAN MASKING
boolean_masking = np.array([10,20,30,40,50,60,70])
print(boolean_masking[boolean_masking >= 25])














3
5
4
3
[10 20 30 40 50 60 70 80]
[10 20]
[20 40 60]
[10 20 30 40 50 60]
[80 70 60 50 40 30 20 10]
[10 30 50]
[30 40 50 60 70]


In [14]:
# Reshaping and Manipulating Arrays 
# change the dimensions withoyt changing data e.g. 1d array ko 2d ma krna ho 
# reshape(rows,coloumn) specify new shape if dimensions match otherwise gives error
rshape = np.array([10,20,30,40,50,60,70,80,90])
print(rshape.reshape(3,3))
# FLATTERING ARRAY
# multi dimensional array ko 1d array  ma krna 
# .ravel() -> veiws returns
# .flatten() -> copy returns
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d.ravel())
print(arr_2d.flatten())


[[10 20 30]
 [40 50 60]
 [70 80 90]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


ADVANCE NUMPY START

In [ ]:
 # ADD OR INSERT
# INSERT:
# np.insert(array,index,value,axis=none)
# array - original array 
# index - possition of the element 
# value - the data wich we ppass 
# axis - in 2d arrays {axis = 0 for row wise insertion, axis = 1 for column wise insertion}

in_array = np.array([10,20,30,40,50,60,70,80,90])
print(in_array)
new_arr = np.insert(in_array,3,100) # 3 is the index and 100 is the value   )
print(new_arr)
arr_2 = np.array([[1,2,9],[4,5,6]])
print(arr_2)
# insert a new column at index 1 
new_arr_2d = np.insert(arr_2, 1,[7,8],axis= 1)
# new_arr_2d = np.insert(arr_2, 1,[7,8],axis= None)
print(new_arr_2d)

# APPEND: 
# np.append(array,value,axis=none)
ap_array = np.array([10,20,30,40,50,60,70,80,90])
new_ar = np.append(ap_array,[30,89,98])
print(new_ar)

# CONCATENATE ARRAY :
# np.concatenate((aray1,array2), axis = 0)
# axis 0 > vertical stacking
# axis 1 > horizontal stacking
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
# arr3 = arr1 + arr2 # this array ading means doing addition
print(arr3)


[10 20 30 40 50 60 70 80 90]
[ 10  20  30 100  40  50  60  70  80  90]
[[1 2 9]
 [4 5 6]]
[[1 7 2 9]
 [4 8 5 6]]
[10 20 30 40 50 60 70 80 90 30 89 98]
[5 7 9]


In [ ]:
# DELETE:
# Original array unchanged
# np.delete(array, index, axis=None)
del_arr = np.array([10,20,30,40,50,60,70])
print(del_arr)
del_new_arr = np.delete(del_arr,3)
print(del_new_arr)

# NUMPY DELETE METHOD ON 2D OR MULTI DIMENSIN ARRAY
del_2d_arr = np.array([[1,2,3,4],[5,6,7,8]])
print(del_2d_arr)
new_del_2d_arr = np.delete(del_2d_arr,1,axis=1)
print(new_del_2d_arr)

[10 20 30 40 50 60 70]
[10 20 30 50 60 70]
[[1 2 3 4]
 [5 6 7 8]]
[[1 3 4]
 [5 7 8]]


STACKING AND SPLITTING ARRAY

In [ ]:
# STACKING:
# combine array vertically and horizontally 
# vstack() row wise
# hstack() column wise
stack_arr_1 = np.array([1,2,3])
stack_arr_2 = np.array([4,5,6])
print(np.vstack((stack_arr_1,stack_arr_2))) #vertically stacking
print(np.hstack((stack_arr_1,stack_arr_2))) # horizontally stacking

# SPLITTING:
# np.split() -> equal parts ma split krna
# np.hsplit() -> horizontally split krna ha 
# np.vsplit() -> vertically split krna ha

split_arr = np.array([10,20,30,40,50,60])
split_h_arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) 
split_v_arr = np.array([[1,2,3,4,5,6],[7,8,9,13,14,15]]) 
print(np.split(split_arr,3)) # 3 equal parts ma split krna ha
print(np.hsplit(split_h_arr,2)) # 2 equal parts ma split krna ha
print(np.vsplit(split_v_arr,2)) # 3 equal parts ma split krna ha

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([10, 20]), array([30, 40]), array([50, 60])]
[array([[1, 2, 3],
       [7, 8, 9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 13, 14, 15]])]


**BROABCASTING AND VECTORISATION**

In [ ]:
# simple problem without broadcasting:
prices = [100,200,300]
final_prices = []
disc = 10 # 10% discount
for price in prices:
    final_prices.append(price - (price *  disc/100))
print(final_prices)


# solving with broadcasting without using loop 
prices_b = np.array([100,200,300])
disc = 10 #scalar single quatity
final_prices_b = prices_b - (prices_b * disc/100)
print(final_prices_b)

# BROADCASTING WITH SINGLE VALUES :
array_broad = np.array([100,200,300,400])
result = array_broad * 2
print(result)

# BROADCASTING WITH 1D ARRAY OR 2D ARRAY 
# 2.--> matching Dimensions 
# 2d array
matrix = np.array([[1,2,3],[4,5,6]]) #2x3 ka matrix
vector = np.array([10,20,30]) # 1d array
results = matrix + vector 
print(results)

# 3. Incomaptible shape







[90.0, 180.0, 270.0]
[ 90. 180. 270.]
[200 400 600 800]
[[11 22 33]
 [14 25 36]]
